// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLittleRPG.Data.Context;

#nullable disable

namespace MyLittleRPG.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20251212011846_AddMonsterRarity")]
    partial class AddMonsterRarity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyLittleRPG.Models.InstanceMonster", b =>
                {
                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<int>("PVMax")
                        .HasColumnType("int");

                    b.Property<int>("PVactuels")
                        .HasColumnType("int");

                    b.Property<int>("niveaux")
                        .HasColumnType("int");

                    b.HasKey("X", "Y");

                    b.HasIndex("MonsterId");

                    b.ToTable("InstanceMonstres");
                });

            modelBuilder.Entity("MyLittleRPG.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("defenseBase")
                        .HasColumnType("int");

                    b.Property<int>("experienceBase")
                        .HasColumnType("int");

                    b.Property<int>("forceBase")
                        .HasColumnType("int");

                    b.Property<int>("pointsVieBase")
                        .HasColumnType("int");

                    b.Property<string>("spriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type1")
                        .HasColumnType("longtext");

                    b.Property<string>("type2")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("MyLittleRPG.Models.Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<int>("NbQuetes")
                        .HasColumnType("int");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PV")
                        .HasColumnType("int");

                    b.Property<int>("PVMax")
                        .HasColumnType("int");

                    b.Property<int>("PositionVilleX")
                        .HasColumnType("int");

                    b.Property<int>("PositionVilleY")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personnages");
                });

            modelBuilder.Entity("MyLittleRPG.Models.PokedexEntry", b =>
                {
                    b.Property<int>("PersonnageId")
                        .HasColumnType("int");

                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.HasKey("PersonnageId", "MonsterId");

                    b.HasIndex("MonsterId");

                    b.ToTable("Pokedex");
                });

            modelBuilder.Entity("MyLittleRPG.Models.QueteNiveauAtteint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPersonnage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NiveauAAtteindre")
                        .HasColumnType("int");

                    b.Property<int>("NiveauPerso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuetesNiveauAtteint");
                });

            modelBuilder.Entity("MyLittleRPG.Models.QueteVaincreMonstres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPersonnage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NbMonstresAVaincre")
                        .HasColumnType("int");

                    b.Property<int>("NbMonstresVaincu")
                        .HasColumnType("int");

                    b.Property<string>("TypeMonstre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("QuetesVaincreMonstres");
                });

            modelBuilder.Entity("MyLittleRPG.Models.QueteVisiterTuile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanceX")
                        .HasColumnType("int");

                    b.Property<int>("DistanceY")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonnage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TileType")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuetesVisiterTuile");
                });

            modelBuilder.Entity("MyLittleRPG.Models.Tile", b =>
                {
                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("estTraversable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("imageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("X", "Y");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("MyLittleRPG.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TempsConexion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isConnected")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MyLittleRPG.Models.InstanceMonster", b =>
                {
                    b.HasOne("MyLittleRPG.Models.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MyLittleRPG.Models.PokedexEntry", b =>
                {
                    b.HasOne("MyLittleRPG.Models.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyLittleRPG.Models.Personnage", "Personnage")
                        .WithMany()
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Personnage");
                });
#pragma warning restore 612, 618
        }
    }
}
