// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLittleRPG.Data.Context;

#nullable disable

namespace MyLittleRPG.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20250908133339_dbinit")]
    partial class dbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyLittleRPG.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("defenseBase")
                        .HasColumnType("int");

                    b.Property<int>("experienceBase")
                        .HasColumnType("int");

                    b.Property<int>("forceBase")
                        .HasColumnType("int");

                    b.Property<int>("pointsVieBase")
                        .HasColumnType("int");

                    b.Property<string>("spriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type1")
                        .HasColumnType("longtext");

                    b.Property<string>("type2")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
